export default {
    extends: ["stylelint-config-standard-scss"],
    rules: {
        // formatting rules are not enforced on the legacy style codebase
        "scss/dollar-variable-colon-space-after": null,
        "rule-empty-line-before": null,
        "scss/double-slash-comment-whitespace-inside": null,
        "selector-pseudo-element-colon-notation": null,
        "scss/double-slash-comment-empty-line-before": null,
        "scss/no-global-function-names": null,
        "block-no-empty": null,
        "value-keyword-case": null,
        "at-rule-empty-line-before": null,
        "scss/dollar-variable-empty-line-before": null,
        "length-zero-no-unit": null,
        "media-feature-range-notation": null,
        "scss/load-no-partial-leading-underscore": null,
        "declaration-empty-line-before": null,
        "comment-empty-line-before": null,
        "scss/operator-no-unspaced": null,
        "shorthand-property-no-redundant-values": null,
        "declaration-block-no-duplicate-properties": null,
        "selector-type-no-unknown": null,
        "selector-type-case": null,
        "keyframes-name-pattern": null,
        "color-function-notation": null,
        "font-family-name-quotes": null,
        "color-function-alias-notation": null,
        "alpha-value-notation": null,
        "selector-class-pattern": null,
        "number-max-precision": null,
        "function-url-quotes": null,
        "font-family-no-missing-generic-family-keyword": null,
        "declaration-property-value-keyword-no-deprecated": null,
        "color-hex-length": null,
        "property-no-deprecated": null,
        "media-feature-name-no-vendor-prefix": null,
        "function-linear-gradient-no-nonstandard-direction": null,
        "declaration-block-single-line-max-declarations": null,
        "declaration-block-no-shorthand-property-overrides": null,
        "declaration-block-no-redundant-longhand-properties": null,
        "import-notation": null,
        "selector-type-case": null,
    },
    ignoreFiles: ["dist/**", "node_modules/**", "compiled/**"],
};
