import { describe, expect, test } from "vitest";
// The library, not the CLI wrapper: `scripts/convert-to-iiif.mjs` is a thin
// file-I/O shell around this function (tests/iiif-roundtrip.test.ts covers the
// wrapper and the generated fixtures).
import { storymapToManifest } from "../src/storymap/to-iiif";
import { manifestToStorymapData } from "../src/storymap/iiif";
import type { StorymapGeoreference, StorymapOverlayLayer } from "../src/types";

/**
 * The writer half of the mapping.
 *
 * tests/iiif-roundtrip.test.ts pins the two properties that need every fixture
 * — regenerating one is a no-op, and a manifest reads back as the storymap it
 * came from — so it is the right place to catch a drift. What it cannot do is
 * say *what* a manifest is supposed to contain: it only compares two outputs.
 *
 * These tests are the other half. Each one asserts the structure the mapping
 * doc specifies for a document shape, so a change that silently degrades a
 * manifest (a Range that loses its canvases, a credit that stops being
 * labelled, a bbox that stops being a Polygon) fails here with a name instead
 * of as a fixture diff somebody has to read.
 */

/** The painting annotation of the nth canvas. */
function annotation(
    manifest: ReturnType<typeof storymapToManifest>,
    index: number,
): Record<string, unknown> {
    const canvas = manifest.items[index] as unknown as {
        items: { items: Record<string, unknown>[] }[];
    };
    return canvas.items[0].items[0] as Record<string, unknown>;
}

/** The map configuration service, or null when the document configures no map. */
function mapConfig(
    manifest: ReturnType<typeof storymapToManifest>,
): Record<string, unknown> | null {
    const service = manifest.service?.[0];
    return (service as Record<string, unknown> | undefined) ?? null;
}

const LAOCOON_IMAGE =
    "https://iiif.io/api/image/3.0/example/reference/28473c77da3deebe4375c3a50572d9d3-laocoon/full/max/0/default.jpg";

describe("storymapToManifest: the minimal document", () => {
    const manifest = storymapToManifest("minimal", {
        storymap: {
            slides: [
                { text: { headline: "Only text" }, media: { url: "" } },
                {
                    text: { headline: "A picture", text: "With a body." },
                    media: {
                        url: "https://example.org/photo.jpg",
                        caption: "A caption",
                        credit: "A credit",
                        alt: "Alt text",
                        thumb: "https://example.org/thumb.png",
                    },
                },
            ],
        },
    });

    test("is a paged Manifest labelled with the document name", () => {
        expect(manifest.type).toBe("Manifest");
        expect(manifest.label).toEqual({ none: ["minimal"] });
        expect(manifest.behavior).toEqual(["paged"]);
        expect(manifest.id).toBe("https://example.org/storymap/minimal");
    });

    test("carries the linked data contexts, navPlace first", () => {
        // navplace §3.1 requires the extension's context *before* the
        // Presentation 3 one, so the order is a MUST and not a preference
        expect(manifest["@context"]).toEqual([
            "http://iiif.io/api/extension/navplace/context.json",
            "http://iiif.io/api/presentation/3/context.json",
            "https://cmahnke.github.io/StoryMapJS/navplace-properties.json",
            "https://cmahnke.github.io/StoryMapJS/context.json",
        ]);
    });

    test("records the converter in metadata, not as the provider", () => {
        expect(manifest.metadata).toEqual([
            { label: { none: ["Generated by"] }, value: { none: ["StoryMapJS"] } },
        ]);
        expect(manifest.requiredStatement).toBeUndefined();
    });

    test("has one canvas per slide, numbered from 1", () => {
        expect(manifest.items).toHaveLength(2);
        expect(manifest.items.map((canvas) => canvas.id)).toEqual([
            "https://example.org/storymap/minimal/canvas/1",
            "https://example.org/storymap/minimal/canvas/2",
        ]);
    });

    test("a non-image map gets a nominal 1080×1080 canvas", () => {
        expect(manifest.items[0]?.width).toBe(1080);
        expect(manifest.items[0]?.height).toBe(1080);
    });

    test("the headline is the canvas label and the text its summary", () => {
        expect(manifest.items[0]?.label).toEqual({ none: ["Only text"] });
        expect(manifest.items[0]?.summary).toBeUndefined();
        expect(manifest.items[1]?.label).toEqual({ none: ["A picture"] });
        expect(manifest.items[1]?.summary).toEqual({ none: ["With a body."] });
    });

    test("a slide with no media URL paints its own text", () => {
        // a storymap slide's `media.url` is optional and a text-only slide is
        // normal, so the canvas still has a body
        expect(annotation(manifest, 0).body).toEqual({
            type: "TextualBody",
            format: "text/html",
            value: "",
        });
    });

    test("a media URL is a typed content resource", () => {
        expect(annotation(manifest, 1).body).toEqual({
            id: "https://example.org/photo.jpg",
            type: "Image",
            format: "image/jpeg",
        });
    });

    test("caption, credit and alt text are the annotation's own properties", () => {
        // §2.7: a `storymap:mediaCaption` / `mediaCredit` / `mediaAlt` term
        // would be a dropped term today, and P3 has a home for each
        const paint = annotation(manifest, 1);
        expect(paint.label).toEqual({ none: ["A caption"] });
        expect(paint.requiredStatement).toEqual({
            label: { none: ["Credit"] },
            value: { none: ["A credit"] },
        });
        expect(paint.accessibilitySummary).toEqual({ none: ["Alt text"] });
    });

    test("the annotation targets its canvas", () => {
        expect(annotation(manifest, 1).target).toBe(
            "https://example.org/storymap/minimal/canvas/2",
        );
    });

    test("media.thumb is a canvas thumbnail list", () => {
        expect(manifest.items[1]?.thumbnail).toEqual([
            { id: "https://example.org/thumb.png", type: "Image", format: "image/png" },
        ]);
        expect(manifest.items[0]?.thumbnail).toBeUndefined();
    });

    test("a document with no map configuration gets no service", () => {
        expect(manifest.service).toBeUndefined();
        expect(manifest.navPlace).toBeUndefined();
        expect(manifest.structures).toBeUndefined();
    });
});

describe("storymapToManifest: map configuration", () => {
    test("a keyword basemap is storymap:basemap, a tile template is TileJSON", () => {
        const keyword = storymapToManifest("keyword", {
            storymap: { map_type: "osm:standard", slides: [] },
        });
        expect(mapConfig(keyword)?.["storymap:basemap"]).toBe("osm:standard");
        expect(mapConfig(keyword)?.tilejson).toBeUndefined();

        // `map_type` used to be both a keyword and a URL template; §2.9 gave
        // the template TileJSON's `tiles`
        const tiles = storymapToManifest("tiles", {
            storymap: { map_type: "https://tiles.example.org/{z}/{x}/{y}.png", slides: [] },
        });
        expect(mapConfig(tiles)?.tilejson).toEqual({
            tiles: "https://tiles.example.org/{z}/{x}/{y}.png",
        });
        expect(mapConfig(tiles)?.["storymap:basemap"]).toBeUndefined();
    });

    test("a zoomify pyramid becomes an iiif image map", () => {
        // the legacy zoomify definition is not carried: nothing reads it
        const manifest = storymapToManifest("zoom", {
            storymap: {
                map_type: "zoomify",
                zoomify: { path: "tiles/", width: 8000, height: 6000 },
                slides: [{ text: { headline: "One" } }],
            },
        });
        expect(mapConfig(manifest)?.["storymap:basemap"]).toBe("iiif");
        expect(mapConfig(manifest)?.["storymap:mapAsImage"]).toBe(true);
        expect(JSON.stringify(manifest)).not.toContain("tiles/");
    });

    test("an image map paints the IIIF reference image on every canvas", () => {
        // the legacy fixtures' zoomify assets are dead, so the converter
        // substitutes the repo's IIIF reference image
        const manifest = storymapToManifest("image-map", {
            storymap: { map_type: "iiif", slides: [{ text: { headline: "One" } }] },
        });
        expect(annotation(manifest, 0).body).toEqual({
            id: LAOCOON_IMAGE,
            type: "Image",
            format: "image/jpeg",
            width: 2315,
            height: 3000,
            service: [
                {
                    id: "https://iiif.io/api/image/3.0/example/reference/28473c77da3deebe4375c3a50572d9d3-laocoon/info.json",
                    type: "ImageService3",
                    profile: "level2",
                },
            ],
        });
        expect(manifest.items[0]?.width).toBe(2315);
        expect(manifest.items[0]?.height).toBe(3000);
    });

    test("the line style block and the rest of the terms are carried verbatim", () => {
        const manifest = storymapToManifest("styled", {
            storymap: {
                map_type: "osm:standard",
                show_lines: true,
                line_color: "#c0392b",
                line_color_inactive: "#7f8c8d",
                line_weight: 3,
                line_opacity: 0.8,
                line_dash: "6 4",
                line_join: "round",
                line_follows_path: true,
                show_history_line: true,
                use_custom_markers: true,
                map_area: "left",
                keyboard: true,
                calculate_zoom: true,
                call_to_action: true,
                call_to_action_text: "Begin",
                start_at_slide: 2,
                language: "en",
                font_css: "https://example.org/fonts.css",
                slides: [],
            },
        });
        const config = mapConfig(manifest) ?? {};
        expect(config).toMatchObject({
            "storymap:showLines": true,
            "storymap:lineColor": "#c0392b",
            "storymap:lineColorInactive": "#7f8c8d",
            "storymap:lineWeight": 3,
            "storymap:lineOpacity": 0.8,
            "storymap:lineDash": "6 4",
            "storymap:lineJoin": "round",
            "storymap:lineFollowsPath": true,
            "storymap:showHistoryLine": true,
            "storymap:useCustomMarkers": true,
            "storymap:mapArea": "left",
            "storymap:keyboard": true,
            "storymap:calculateZoom": true,
            "storymap:callToAction": true,
            "storymap:callToActionText": "Begin",
            "storymap:startAtSlide": 2,
            "storymap:language": "en",
            "storymap:fontCss": "https://example.org/fonts.css",
        });
    });

    test("a root-level font_css wins over the one inside storymap", () => {
        const manifest = storymapToManifest("fonts", {
            font_css: "https://example.org/root.css",
            storymap: { font_css: "https://example.org/nested.css", slides: [] },
        });
        expect(mapConfig(manifest)?.["storymap:fontCss"]).toBe("https://example.org/root.css");
    });

    test("the service is a Service with the mapconfig profile", () => {
        // the official validator's Manifest schema is additionalProperties:
        // false, which is why the terms travel here rather than on the
        // Manifest itself
        const manifest = storymapToManifest("profiled", {
            storymap: { map_type: "osm:standard", slides: [] },
        });
        expect(manifest.service?.[0]?.id).toBe("https://example.org/storymap/profiled/map-config");
        expect(manifest.service?.[0]?.type).toBe("Service");
        expect(manifest.service?.[0]?.profile).toBe(
            "https://cmahnke.github.io/StoryMapJS/context.json/mapconfig",
        );
    });

    test("a map bbox is a navPlace Polygon on the Manifest", () => {
        const manifest = storymapToManifest("bounded", {
            storymap: { map_bbox: [2.29, 48.85, 2.38, 48.9], slides: [] },
        });
        const feature = manifest.navPlace?.features[0];
        expect(manifest.navPlace?.type).toBe("FeatureCollection");
        expect(feature?.geometry).toEqual({
            type: "Polygon",
            coordinates: [
                [
                    [2.29, 48.85],
                    [2.38, 48.85],
                    [2.38, 48.9],
                    [2.29, 48.9],
                    [2.29, 48.85],
                ],
            ],
        });
        expect(feature?.properties).toEqual({});
    });

    test("an overview extent is a term, not a Polygon", () => {
        const manifest = storymapToManifest("overview", {
            storymap: { overview_extent: [0, 0, 1, 1], slides: [] },
        });
        expect(mapConfig(manifest)?.["storymap:overviewExtent"]).toEqual([0, 0, 1, 1]);
        expect(manifest.navPlace).toBeUndefined();
    });

    test("an attribution is a labelled requiredStatement on the Manifest", () => {
        const manifest = storymapToManifest("credited", {
            storymap: { iiif: { url: "", attribution: "© Example" }, slides: [] },
        });
        expect(manifest.requiredStatement).toEqual({
            label: { none: ["Attribution"] },
            value: { none: ["© Example"] },
        });
    });

    test("a tile-source overlay rides the service, minus its tile templates", () => {
        const overlays: StorymapOverlayLayer[] = [
            { map_type: "https://tiles.example.org/{z}/{x}/{y}.png", opacity: 0.5 },
            { map_type: "osm:humanitarian" },
        ];
        const manifest = storymapToManifest("overlaid", { storymap: { overlays, slides: [] } });
        expect(mapConfig(manifest)?.["storymap:overlays"]).toEqual(overlays);
        // …but the map configuration as a whole is still a service
        expect(manifest.service?.[0]?.profile).toContain("mapconfig");
    });

    test("a location becomes a navPlace Point carrying its marker presentation", () => {
        const manifest = storymapToManifest("located", {
            storymap: {
                slides: [
                    {
                        location: {
                            lat: 48.86,
                            lon: 2.34,
                            name: "Paris",
                            zoom: 12,
                            line: true,
                            icon: "https://example.org/pin.png",
                            iconSize: [30, 40],
                            // an unknown key is not copied
                            secret: "no",
                        },
                    },
                ],
            },
        });
        const feature = manifest.items[0]?.navPlace?.features[0];
        expect(feature?.geometry).toEqual({ type: "Point", coordinates: [2.34, 48.86] });
        expect(feature?.properties).toEqual({
            name: "Paris",
            zoom: 12,
            line: true,
            icon: "https://example.org/pin.png",
            iconSize: [30, 40],
        });
    });

    test("marker presentation survives the round trip", () => {
        // popup and audioBadge are marker presentation with no IIIF
        // vocabulary of their own, so they ride the navPlace properties bag.
        // The writer once omitted them while the reader read them, losing
        // both on storymap -> manifest -> storymap.
        const manifest = storymapToManifest("badged", {
            storymap: {
                slides: [
                    {
                        location: {
                            lat: 48.86,
                            lon: 2.34,
                            popup: true,
                            audioBadge: true,
                        },
                    },
                ],
            },
        });
        const properties = manifest.items[0]?.navPlace?.features[0]?.properties;
        expect(properties?.popup).toBe(true);
        expect(properties?.audioBadge).toBe(true);

        const data = manifestToStorymapData(manifest) as {
            slides: { location?: { popup?: boolean; audioBadge?: boolean } }[];
        };
        expect(data.slides[0]?.location?.popup).toBe(true);
        expect(data.slides[0]?.location?.audioBadge).toBe(true);
    });

    test("a location without coordinates has no navPlace", () => {
        // IIIF has no vocabulary for "a marker with no position"
        const manifest = storymapToManifest("unplaced", {
            storymap: { slides: [{ location: { icon: "https://example.org/pin.png" } }] },
        });
        expect(manifest.items[0]?.navPlace).toBeUndefined();
    });

    test("an image region is an Image API selector on the annotation target", () => {
        const manifest = storymapToManifest("region", {
            storymap: { slides: [{ location: { region: [10, 20, 300, 400] } }] },
        });
        expect(annotation(manifest, 0).target).toEqual({
            type: "SpecificResource",
            source: "https://example.org/storymap/region/canvas/1",
            // the `pixel` prefix says the numbers are source-image pixels
            selector: { type: "ImageApiSelector", value: "xywh=pixel:10,20,300,400" },
        });
    });
});

describe("storymapToManifest: georeferenced overlays", () => {
    const georeference: StorymapGeoreference = {
        url: "https://iiif.example.org/sheet",
        width: 2000,
        height: 1500,
        body: {
            type: "FeatureCollection",
            transformation: { type: "polynomial", options: { order: 1 } },
            features: [
                {
                    type: "Feature",
                    properties: { resourceCoords: [0, 0] },
                    geometry: { type: "Point", coordinates: [2.29, 48.85] },
                },
            ],
        },
    };

    const manifest = storymapToManifest("georeferenced", {
        storymap: {
            overlays: [{ map_type: "osm:standard" }, { attribution: "©.maps", georeference }],
            slides: [{ text: { headline: "One" } }, { text: { headline: "Two" } }],
        },
    });

    function georeferencingAnnotations(index: number): Record<string, unknown>[] {
        const canvas = manifest.items[index] as unknown as { items: { items: unknown[] }[] };
        return canvas.items[0].items.filter(
            (entry) => (entry as { motivation?: string }).motivation === "georeferencing",
        ) as Record<string, unknown>[];
    }

    test("the placement is a georeferencing annotation on the first canvas", () => {
        const annotations = georeferencingAnnotations(0);
        expect(annotations).toHaveLength(1);
        expect(annotations[0]?.id).toBe(
            "https://example.org/storymap/georeferenced/canvas/1/georeferencing/1",
        );
        expect(annotations[0]?.type).toBe("Annotation");
        expect(annotations[0]?.motivation).toBe("georeferencing");
    });

    test("the target is the placed image, as an embedded resource", () => {
        // per the extension, a layer that is not part of the canvas it ships in
        // carries the image it places in `target`
        const annotations = georeferencingAnnotations(0);
        expect(annotations[0]?.target).toEqual({
            id: "https://iiif.example.org/sheet",
            type: "Image",
            width: 2000,
            height: 1500,
            service: [
                {
                    id: "https://iiif.example.org/sheet",
                    type: "ImageService3",
                    profile: "level2",
                },
            ],
        });
    });

    test("the ground control points are the annotation body, verbatim", () => {
        expect(georeferencingAnnotations(0)[0]?.body).toEqual(georeference.body);
    });

    test("the attribution is a requiredStatement, where P3 puts it", () => {
        expect(georeferencingAnnotations(0)[0]?.requiredStatement).toEqual({
            label: { none: ["Attribution"] },
            value: { none: ["©.maps"] },
        });
    });

    test("a tile overlay is not a georeferencing annotation", () => {
        // the fixture carries two overlays: a tile layer and a placed sheet.
        // Only the sheet becomes an annotation; the tile layer stays in the
        // mapconfig service, where a tile template belongs.
        expect(georeferencingAnnotations(0)).toHaveLength(1);
        const overlays = mapConfig(manifest)?.["storymap:overlays"] as { map_type?: string }[];
        expect(overlays?.some((entry) => entry.map_type === "osm:standard")).toBe(true);
    });

    test("the painting annotation and the placements share one page", () => {
        const canvas = manifest.items[0] as unknown as { items: { items: unknown[] }[] };
        expect(canvas.items[0].items).toHaveLength(2);
    });

    test("only the first canvas carries them; the reader collects from every one", () => {
        expect(georeferencingAnnotations(1)).toEqual([]);
    });
});

describe("storymapToManifest: group, date and background", () => {
    const manifest = storymapToManifest("annotated", {
        storymap: {
            slides: [
                { group: "Chapter one", date: "Aug 23", text: { headline: "One" } },
                { text: { headline: "Two" }, date: "1790-2010" },
                {
                    group: "Chapter two",
                    date: "",
                    text: { headline: "Three" },
                    background: { url: "https://example.org/bg.jpg", color: "#123456" },
                },
            ],
        },
    });

    test("a group is a Range over the canvases it contains", () => {
        expect(manifest.structures).toEqual([
            {
                id: "https://example.org/storymap/annotated/range/1",
                type: "Range",
                label: { none: ["Chapter one"] },
                items: ["https://example.org/storymap/annotated/canvas/1"],
            },
            {
                id: "https://example.org/storymap/annotated/range/2",
                type: "Range",
                label: { none: ["Chapter two"] },
                items: ["https://example.org/storymap/annotated/canvas/3"],
            },
        ]);
    });

    test("an ungrouped slide belongs to no Range", () => {
        const ids = manifest.structures?.flatMap((range) => range.items) ?? [];
        expect(ids).not.toContain("https://example.org/storymap/annotated/canvas/2");
    });

    test("a date is navDate, carried verbatim", () => {
        // P3 constrains navDate to a plain string and applies no format
        // constraint, so "Aug 23" and a year range both pass
        expect(manifest.items[0]?.navDate).toBe("Aug 23");
        expect(manifest.items[1]?.navDate).toBe("1790-2010");
    });

    test("an empty date is absent, not an empty navDate", () => {
        expect(manifest.items[2]?.navDate).toBeUndefined();
    });

    test("an image and a colour background is one annotation with two bodies", () => {
        expect(manifest.items[2]?.background).toEqual({
            id: "https://example.org/storymap/annotated/canvas/3/background",
            type: "Annotation",
            motivation: "painting",
            body: [
                { id: "https://example.org/bg.jpg", type: "Image", format: "image/jpeg" },
                { type: "Color", value: "#123456" },
            ],
            target: "https://example.org/storymap/annotated/canvas/3",
        });
    });

    test("a slide with no background has no background annotation", () => {
        expect(manifest.items[0]?.background).toBeUndefined();
    });

    test("a bare string background is a colour", () => {
        const coloured = storymapToManifest("tinted", {
            storymap: { slides: [{ background: "#abcdef" }] },
        });
        expect((coloured.items[0]?.background?.body as { type: string }).type).toBe("Color");
    });
});

describe("storymapToManifest: resilience", () => {
    test("an empty document is a valid, empty Manifest", () => {
        const manifest = storymapToManifest("empty", {});
        expect(manifest.items).toEqual([]);
        expect(manifest.structures).toBeUndefined();
        expect(manifest.service).toBeUndefined();
    });

    test("no slide, no canvas, no exception", () => {
        expect(storymapToManifest("no-slides", { storymap: { map_type: "osm" } }).items).toEqual(
            [],
        );
    });

    test("a page-embedded URL is a typed text reference", () => {
        // tweets, Wikipedia and photo pages: the viewer decides how to render
        // them, the manifest only carries a typed pointer
        const manifest = storymapToManifest("embedded", {
            storymap: {
                slides: [{ media: { url: "https://twitter.com/example/status/1" } }],
            },
        });
        expect(annotation(manifest, 0).body).toEqual({
            id: "https://twitter.com/example/status/1",
            type: "Text",
            format: "text/html",
        });
    });

    test("a video host is typed Video, a sound host Sound", () => {
        const video = storymapToManifest("video", {
            storymap: { slides: [{ media: { url: "https://www.youtube.com/watch?v=abc" } }] },
        });
        expect(annotation(video, 0).body).toEqual({
            id: "https://www.youtube.com/watch?v=abc",
            type: "Video",
        });
        const sound = storymapToManifest("sound", {
            storymap: { slides: [{ media: { url: "https://soundcloud.com/x/y" } }] },
        });
        expect(annotation(sound, 0).body).toEqual({
            id: "https://soundcloud.com/x/y",
            type: "Sound",
        });
    });

    test("an overview slide keeps the one term that has no P3 home", () => {
        const manifest = storymapToManifest("overview-slide", {
            storymap: { slides: [{ type: "overview" }, { type: "overviewstart" }] },
        });
        expect(manifest.items[0]?.["storymap:type"]).toBe("overview");
        expect(manifest.items[1]?.["storymap:type"]).toBeUndefined();
    });

    test("srcset and sizes stay terms; the rest of the media block is standard", () => {
        const manifest = storymapToManifest("responsive", {
            storymap: {
                slides: [
                    {
                        media: {
                            url: "https://example.org/photo.jpg",
                            srcset: "https://example.org/photo@2x.jpg 2x",
                            sizes: "100vw",
                        },
                    },
                ],
            },
        });
        expect(manifest.items[0]?.["storymap:mediaSrcset"]).toBe(
            "https://example.org/photo@2x.jpg 2x",
        );
        expect(manifest.items[0]?.["storymap:mediaSizes"]).toBe("100vw");
    });

    test("non-object slides are skipped, not painted or crashed on", () => {
        // A hand-built document can carry anything here. null used to throw
        // a raw TypeError on slide.text; 42 painted an empty canvas.
        const manifest = storymapToManifest("junk", {
            storymap: {
                slides: [null, 42, { text: { headline: "Real", text: "" } }] as unknown as never[],
            },
        });
        expect(manifest.items).toHaveLength(1);
    });

    test("a non-string media.url emits an empty body, not the caption", () => {
        // Painting the caption as the body claims it IS the content — and the
        // summary already carries it, so the reader would read it back as
        // media.url, silently changing its type.
        const manifest = storymapToManifest("bad-url", {
            storymap: {
                slides: [{ text: { text: "<p>hello</p>" }, media: { url: 42 } } as never],
            },
        });
        expect(annotation(manifest, 0).body).toEqual({
            type: "TextualBody",
            format: "text/html",
            value: "",
        });
    });

    test("a malformed georeference is not emitted", () => {
        // A string width or an infinite height would reach the annotation
        // target, which declares numbers — on the branch the validator
        // whitelists out, so nothing downstream would catch it.
        for (const georeference of [
            { url: "https://iiif.example.org/s", width: "10", height: 100 },
            { url: "https://iiif.example.org/s", width: 10, height: Infinity },
            { url: "https://iiif.example.org/s", width: 0, height: 100 },
        ]) {
            const manifest = storymapToManifest("bad-geo", {
                storymap: {
                    overlays: [{ georeference } as never],
                    slides: [{ text: { headline: "One" } }],
                },
            });
            const canvas = manifest.items[0] as unknown as { items: { items: unknown[] }[] };
            expect(
                canvas.items[0].items.filter(
                    (entry) => (entry as { motivation?: string }).motivation === "georeferencing",
                ),
            ).toEqual([]);
        }
    });

    test("an infinite coordinate does not reach navPlace", () => {
        const manifest = storymapToManifest("inf", {
            storymap: {
                slides: [{ location: { lat: Infinity, lon: 10 } }] as never[],
            },
        });
        expect(manifest.items[0]?.navPlace).toBeUndefined();
    });

    test("a .constructor URL is not an Image", () => {
        // A bare object lookup hits Object.prototype, which is truthy.
        const manifest = storymapToManifest("ctor", {
            storymap: { slides: [{ media: { url: "https://example.org/a.constructor" } }] },
        });
        expect(annotation(manifest, 0).body).toEqual({
            id: "https://example.org/a.constructor",
            type: "Text",
            format: "text/html",
        });
    });

    test("each manifest gets its own @context array", () => {
        const a = storymapToManifest("a", { storymap: { slides: [] } });
        const b = storymapToManifest("b", { storymap: { slides: [] } });
        expect(a["@context"]).not.toBe(b["@context"]);
        expect(a["@context"]).toEqual(b["@context"]);
        (a["@context"] as string[]).push("BOGUS");
        expect(b["@context"]).not.toContain("BOGUS");
    });

    test("an overlay with map_type and georeference is emitted once", () => {
        const manifest = storymapToManifest("dual", {
            storymap: {
                overlays: [
                    {
                        map_type: "osm:standard",
                        georeference: {
                            url: "https://iiif.example.org/s",
                            width: 2000,
                            height: 1500,
                            body: { type: "FeatureCollection", features: [] },
                        },
                    },
                ],
                slides: [{ text: { headline: "One" } }],
            },
        });
        // the georeference rides the annotation, not the service entry
        const overlays = (
            manifest.service?.[0] as unknown as { "storymap:overlays"?: Record<string, unknown>[] }
        )?.["storymap:overlays"];
        expect(overlays?.[0]).not.toHaveProperty("georeference");
        const canvas = manifest.items[0] as unknown as {
            items: { items: { motivation?: string }[] }[];
        };
        expect(
            canvas.items[0].items.filter((entry) => entry.motivation === "georeferencing"),
        ).toHaveLength(1);
    });

    test("a non-string map_type is coerced before writing", () => {
        const manifest = storymapToManifest("num", {
            storymap: { map_type: 5, slides: [] } as never,
        });
        const service = manifest.service?.[0] as unknown as Record<string, unknown>;
        expect(service["storymap:basemap"]).toBe("5");
    });

    test("a wrong-typed mapconfig term is copied, then dropped on read-back", () => {
        // The writer is a faithful copy of the storymap — even schema-invalid
        // values — and the reader narrows each term with asString/asNumber/
        // asBoolean, which return null on a type mismatch. So line_weight
        // "2" survives the manifest but not the round trip. That input was
        // already invalid per the schema; this pins the behaviour as a
        // decision rather than leaving it an accident.
        const manifest = storymapToManifest("mistyped", {
            storymap: { line_weight: "2", slides: [] } as never,
        });
        const service = manifest.service?.[0] as unknown as Record<string, unknown>;
        expect(service["storymap:lineWeight"]).toBe("2");

        const data = manifestToStorymapData(manifest) as { line_weight?: unknown };
        expect(data.line_weight).toBeUndefined();
        expect("line_weight" in data).toBe(false);
    });
});
