import { describe, expect, test } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
// The CLI wrapper is imported, not run: its main() is behind an
// invoked-directly guard precisely so this works.
import { storymapToManifest } from "../scripts/convert-to-iiif.mjs";
import { manifestToStorymapData } from "../src/storymap/iiif";
import type { StorymapData, StorymapSlide } from "../src/types";

/**
 * The IIIF fixtures are generated, not hand-written, so "the 52 manifests
 * still validate unchanged in meaning" (docs/plans/iiif-interop.md §2) has to
 * be checkable rather than a diff somebody reads. Three properties:
 *
 *  1. **drift** — regenerating a fixture reproduces the committed file
 *     byte-for-byte, so a hand edit to a generated file is caught.
 *  2. **round trip** — a manifest converts back to the storymap it came from.
 *  3. **context agreement** — every term the converter emits is declared in
 *     public/context.json, and every declared term is either emitted or on an
 *     explicit list of terms no fixture exercises.
 *
 * The round trip is not byte equality and must not pretend to be. The
 * differences below are each deliberate or unavoidable, and the list is the
 * point: a new one appearing is a finding, not a rounding error.
 */

const EXAMPLES = join(process.cwd(), "public/examples");
const MANIFESTS = join(process.cwd(), "public/examples-iiif");

/** Hand-authored: a georeferenced layer is manifest-only, so nothing to convert from. */
const HAND_AUTHORED = new Set([
    "georeferenced-layer",
    "georeferenced-layer-unsupported",
    "annotated-image",
]);

/**
 * Every manifest we ship: the generated ones plus the hand-authored ones.
 * The sweep tests below must iterate this list, not the directory, so a
 * stray file landing in public/examples-iiif/ (a one-off CLI run, an editor
 * backup) cannot be swept into the suite or the validator unnoticed.
 */
function shippedManifests(): string[] {
    return [
        ...sourceFixtures().map((n) => n + ".json"),
        ...[...HAND_AUTHORED].map((n) => n + ".json"),
    ];
}

/** Canonical JSON, so comparison is structural and ignores key order. */
function canon(value: unknown): string {
    if (Array.isArray(value)) return `[${value.map(canon).join(",")}]`;
    if (value !== null && typeof value === "object") {
        const record = value as Record<string, unknown>;
        return `{${Object.keys(record)
            .sort()
            .map((k) => `${JSON.stringify(k)}:${canon(record[k])}`)
            .join(",")}}`;
    }
    return JSON.stringify(value) ?? "null";
}

function sourceFixtures(): string[] {
    return readdirSync(EXAMPLES)
        .filter((f) => f.endsWith(".json"))
        .map((f) => f.replace(/\.json$/, ""));
}

/**
 * Differences that are expected, and why. Each is a place where the manifest
 * cannot carry the storymap's exact value.
 *
 * `root.zoomify`, `root.map_type` — the converter deliberately rewrites a
 *   `zoomify` pyramid to an IIIF image map; the legacy definition is not
 *   carried because nothing reads it.
 * `root.iiif.attribution` — the manifest always labels its
 *   `requiredStatement`, so the bare storymap attribution comes back prefixed
 *   with "Attribution: ". §2.1 made this deliberate.
 * `root.map_subdomains` — an empty string is dropped as absent.
 * `root.map_mini` — the minimap toggle has no IIIF vocabulary at all.
 * `slide.background.opacity` — accepted by the reader, never rendered, and the
 *   term has no standard slot to carry it.
 * `slide.date`, `slide.text.text` — an empty string is dropped as absent.
 * `slide.location` — a location with marker presentation but **no** lat/lon
 *   (an icon without a position) cannot become a navPlace Point, so it is
 *   lost. IIIF has no vocabulary for "a marker with no location".
 * `slide.media.url` — a slide with an empty media block paints a
 *   TextualBody carrying the slide text, so the url comes back as that text.
 * `slide.uniqueid` — the converter emits no id; the reader synthesises the
 *   canvas id (§2.3), which is the point of that change.
 * `root.metadata` — the converter writes a "Generated by: StoryMapJS" pair and
 *   the reader hands it back, which a storymap never had a field for (§3.2).
 * `root.title` — a P3 Manifest `label` is required, so the converter uses the
 *   fixture's file name; a storymap with no `title` field gets one back.
 * `root.tilejson` — the reader now reports the TileJSON it found (§2.9). The
 *   information duplicates `map_type`, which the storymap already had.
 * `root.map_as_image` — the two legacy `map_type: "zoomify"` fixtures convert
 *   to `basemap: "iiif"` + `mapAsImage: true`, so `map_as_image` comes back as
 *   a field the storymap never set. (`root.map_type` covers the other half of
 *   that same replacement.)
 */
const EXPECTED_DIFFERENCES = new Set([
    "root.iiif",
    "root.map_as_image",
    "root.metadata",
    "root.tilejson",
    "root.title",
    "root.map_subdomains",
    "root.map_type",
    "root.map_mini",
    "root.zoomify",
    "slide.background",
    "slide.date",
    "slide.location",
    "slide.media",
    "slide.text",
    "slide.uniqueid",
]);

describe("IIIF fixture generation", () => {
    const names = sourceFixtures();

    test("finds the source fixtures", () => {
        expect(names.length).toBeGreaterThan(40);
    });

    test("regenerating a fixture is a no-op", () => {
        // a hand edit to a generated file would otherwise survive silently,
        // and the next `npm run convert:iiif` would revert it
        const drifted: string[] = [];
        for (const name of names) {
            const legacy = JSON.parse(readFileSync(join(EXAMPLES, `${name}.json`), "utf8"));
            const produced = `${JSON.stringify(storymapToManifest(name, legacy), null, 4)}\n`;
            let committed: string;
            try {
                committed = readFileSync(join(MANIFESTS, `${name}.json`), "utf8");
            } catch {
                drifted.push(`${name}: no manifest`);
                continue;
            }
            if (committed !== produced) drifted.push(name);
        }
        expect(drifted, `run npm run convert:iiif to regenerate: ${drifted}`).toEqual([]);
    });

    test("only the hand-authored fixtures do not convert", () => {
        // every source fixture having a manifest is already pinned by the
        // no-op test above (a missing file lands in its `drifted` list), so
        // this one only checks the exceptions are genuinely manifest-only
        // features with nothing to convert from
        for (const name of HAND_AUTHORED) {
            expect(names).not.toContain(name);
        }
    });
});

describe("manifest -> storymap round trip", () => {
    const names = sourceFixtures().filter((n) => !HAND_AUTHORED.has(n));

    test("the differences are only the documented ones", () => {
        const found = new Map<string, string[]>();
        const note = (key: string, example: string) => {
            if (!found.has(key)) found.set(key, []);
            const list = found.get(key) as string[];
            if (list.length < 2) list.push(example);
        };

        for (const name of names) {
            const source = JSON.parse(readFileSync(join(EXAMPLES, `${name}.json`), "utf8"))
                .storymap as Record<string, unknown>;
            const out = manifestToStorymapData(
                storymapToManifest(name, { storymap: source }),
            ) as StorymapData;

            // the union, not just the source's keys: a key the reader *adds*
            // is as much a difference as one it drops, and iterating only
            // the source let `metadata` through unnoticed when §3.2 introduced
            // it
            for (const key of new Set([...Object.keys(source), ...Object.keys(out)])) {
                if (key === "slides") continue;
                if (canon(out[key as keyof StorymapData]) !== canon(source[key])) {
                    note(`root.${key}`, name);
                }
            }

            const sourceSlides = (source.slides ?? []) as StorymapSlide[];
            const outSlides = out.slides ?? [];
            if (outSlides.length !== sourceSlides.length) {
                note("slides.length", `${name}: ${sourceSlides.length} -> ${outSlides.length}`);
            }
            for (let i = 0; i < Math.min(sourceSlides.length, outSlides.length); i++) {
                for (const key of new Set([
                    ...Object.keys(sourceSlides[i]),
                    ...Object.keys(outSlides[i] ?? {}),
                ])) {
                    if (
                        canon(sourceSlides[i][key as keyof StorymapSlide]) !==
                        canon(outSlides[i]?.[key])
                    ) {
                        note(`slide.${key}`, `${name}[${i}]`);
                    }
                }
            }
        }

        // an undocumented difference is a finding: either the converter is
        // lossy somewhere new, or a legitimate difference needs documenting
        expect([...found.keys()].filter((k) => !EXPECTED_DIFFERENCES.has(k))).toEqual([]);
        // and the list itself must not rot: every entry should still occur
        const unused = [...EXPECTED_DIFFERENCES].filter((k) => !found.has(k));
        expect(unused, "EXPECTED_DIFFERENCES lists a difference that no longer occurs").toEqual([]);
    });

    test("the slides that do round-trip carry their media", () => {
        // The fields a tour depends on: a slide keeps its media url and its
        // caption/credit/alt. Image maps are excluded — the converter
        // deliberately repaints every canvas of an image map with the IIIF
        // reference image, because the original pyramid assets are dead, so
        // their per-slide media is not expected to survive.
        let checked = 0;
        for (const name of names) {
            const document = JSON.parse(readFileSync(join(EXAMPLES, `${name}.json`), "utf8"))
                .storymap as { slides?: StorymapSlide[]; map_type?: string };
            if (document.map_type === "zoomify" || document.map_type === "iiif") continue;
            const source = document;
            const out = manifestToStorymapData(storymapToManifest(name, { storymap: source }));
            const sourceSlides = source.slides ?? [];
            for (let i = 0; i < Math.min(sourceSlides.length, out.slides.length); i++) {
                const want = sourceSlides[i]?.media;
                if (!want?.url) continue;
                const got = out.slides[i]?.media;
                expect(got?.url, `${name}[${i}] media.url`).toBe(want.url);
                // Every string crosses a language map, and flattenLanguageMap
                // trims, so leading/trailing whitespace is normalised away.
                // A fixture caption that ends in a space comes back without it.
                if (want.caption) {
                    expect(got?.caption?.trim(), `${name}[${i}] caption`).toBe(
                        String(want.caption).trim(),
                    );
                }
                if (want.alt) {
                    expect(got?.alt?.trim(), `${name}[${i}] alt`).toBe(String(want.alt).trim());
                }
                if (want.credit) {
                    // A credit is written as a *labelled* `requiredStatement`,
                    // because P3's shape is `{label, value}` and §2.1 keeps the
                    // label. So the round trip is not the identity for this one
                    // field: it comes back as "Credit: <credit>". The value
                    // itself must still be intact. (An earlier version also
                    // asserted the exact string against a right-hand side
                    // built from the value under test, which could not fail.)
                    expect(got?.credit, `${name}[${i}] credit value`).toContain(want.credit);
                }
                checked++;
            }
        }
        expect(checked).toBeGreaterThan(50);
    });
});

describe("context agreement", () => {
    test("every emitted term is declared, and every declared term is accounted for", () => {
        // context.json keys terms by their bare name and states the full IRI as
        // the value, so the declared set has to be built from the values (or an
        // "@id" for the two object-valued ones), not the keys
        const context = (
            JSON.parse(readFileSync(join(process.cwd(), "public/context.json"), "utf8")) as {
                "@context": Record<string, unknown>;
            }
        )["@context"];
        const declared = new Set<string>();
        for (const [key, value] of Object.entries(context)) {
            if (key.startsWith("@") || key === "storymap") continue;
            const iri = typeof value === "string" ? value : (value as { "@id"?: string })["@id"];
            if (typeof iri === "string" && iri.startsWith("storymap:")) declared.add(iri);
        }

        // Derived from what the converter actually produces, not from a list
        // in the source — otherwise the two could agree while both are wrong.
        const emitted = new Set<string>();
        const walk = (node: unknown) => {
            if (Array.isArray(node)) {
                for (const entry of node) walk(entry);
                return;
            }
            if (node === null || typeof node !== "object") return;
            for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
                if (key.startsWith("storymap:")) emitted.add(key);
                walk(value);
            }
        };
        for (const name of sourceFixtures()) {
            if (HAND_AUTHORED.has(name)) continue;
            const legacy = JSON.parse(readFileSync(join(EXAMPLES, `${name}.json`), "utf8"));
            walk(storymapToManifest(name, legacy));
        }

        // a term the converter writes but the context does not declare is a
        // manifest that no JSON-LD processor can resolve
        const undeclared = [...emitted].filter((t) => !declared.has(t));
        expect(undeclared, "emitted but not declared in public/context.json").toEqual([]);

        // Declared terms no fixture exercises. Not an error — a term can be
        // valid without a fixture shipping it — but it should be a deliberate
        // list rather than "whatever is left over", so that adding coverage
        // shows up as a diff here.
        //
        // The categories: map vendor configuration that needs a credential or
        // a paid style (no bundled key by design), presentation options with
        // no interesting storymap to show them on, and the two hand-authored
        // georeferenced manifests, which are manifest-only features with
        // nothing in public/examples to convert from.
        const NOT_EXERCISED_BY_A_FIXTURE = new Set([
            // need a credential or a vendor style
            "storymap:mapAccessToken",
            // no fixture sets these; the code path is covered by unit tests
            "storymap:mapBackgroundColor",
            "storymap:mapCenterOffset",
            "storymap:callToActionText",
            "storymap:calculateZoom",
            "storymap:lineFollowsPath",
            "storymap:showHistoryLine",
            "storymap:lineColor",
            "storymap:lineColorInactive",
            "storymap:lineWeight",
            "storymap:lineOpacity",
            "storymap:lineDash",
            "storymap:lineJoin",
        ]);
        const unaccounted = [...declared].filter(
            (t) => !emitted.has(t) && !NOT_EXERCISED_BY_A_FIXTURE.has(t),
        );
        expect(unaccounted, "declared in context.json but neither emitted nor listed").toEqual([]);
        // and the allowlist must not rot either
        const unused = [...NOT_EXERCISED_BY_A_FIXTURE].filter(
            (t) => !declared.has(t) || emitted.has(t),
        );
        expect(unused, "NOT_EXERCISED_BY_A_FIXTURE is stale").toEqual([]);
    });

    test("the mapping doc's context block is public/context.json", () => {
        // docs/storymap-as-iiif-manifest.md says its block is "the exact same
        // content the fixtures reference", which is only true if something
        // checks it: §2 removed nine terms and added basemap, and a stale copy
        // in the prose is how a host ends up authoring a manifest that no
        // longer validates
        const doc = readFileSync(join(process.cwd(), "docs/storymap-as-iiif-manifest.md"), "utf8");
        const block = /```json\n(\{\n {4}"@context"[\s\S]*?\n\})\n```/.exec(doc);
        expect(block, "the mapping doc has no @context block").not.toBeNull();
        const inDoc = (JSON.parse(block?.[1] ?? "{}") as { "@context": unknown })["@context"];
        const onDisk = (
            JSON.parse(readFileSync(join(process.cwd(), "public/context.json"), "utf8")) as {
                "@context": unknown;
            }
        )["@context"];
        expect(inDoc).toEqual(onDisk);
    });

    test("the navPlace properties context describes exactly the properties the reader copies", () => {
        // §3.3: the navPlace extension asks for a Feature `properties` bag to
        // be described by a registered extension or a local linked-data
        // context, and a client that finds a property it does not understand
        // must ignore it. So the context and the reader's copy list have to
        // agree — the plan called that a conformance gap in its own right.
        const context = JSON.parse(
            readFileSync(join(process.cwd(), "public/navplace-properties.json"), "utf8"),
        )["@context"] as Record<string, unknown>;
        // the properties are ours, but they still belong under the project's
        // real, already-published namespace. The first version of this file
        // coined `…/iiif/storymap/navplace#`, which is a URL that 404s to a
        // personal site's error page — a term IRI pointing at nothing.
        const storymapNamespace = (
            JSON.parse(readFileSync(join(process.cwd(), "public/context.json"), "utf8")) as {
                "@context": { storymap: string };
            }
        )["@context"].storymap;
        expect(context["storymap_navplace"]).toBe(storymapNamespace);
        // and every term must expand to an IRI under it, not a bare word
        for (const [term, value] of Object.entries(context)) {
            if (term.startsWith("@") || term === "xsd" || term === "storymap_navplace") {
                continue;
            }
            const iri = typeof value === "string" ? value : (value as { "@id": string })["@id"];
            expect(iri, term).toMatch(/^storymap_navplace:/);
        }
        const described = Object.keys(context).filter(
            (term) => !term.startsWith("@") && term !== "xsd" && !term.startsWith("storymap_"),
        );
        // the same list the reader copies out of navPlace properties
        const READ = [
            "name",
            "zoom",
            "line",
            "icon",
            "iconSize",
            "image",
            "use_custom_marker",
            "popup",
            "audioBadge",
        ];
        expect([...described].sort()).toEqual([...READ].sort());
    });

    test("the navPlace context precedes the Presentation 3 context, as the extension requires", () => {
        // navplace §3.1: "The navPlace extension linked data context must be
        // included before the IIIF Presentation API 3 linked data context on
        // the top-level object." Every manifest here carries a navPlace, so
        // this is a MUST on all of them — and every one of them had it
        // backwards, Presentation 3 first.
        const NAVPLACE = "navplace/context.json";
        const P3 = "presentation/3/context.json";
        const wrong: string[] = [];
        for (const file of shippedManifests()) {
            const context = (
                JSON.parse(
                    readFileSync(join(process.cwd(), "public/examples-iiif", file), "utf8"),
                ) as {
                    "@context": string[];
                }
            )["@context"];
            if (!Array.isArray(context)) continue;
            const navplace = context.findIndex((c) => c.includes(NAVPLACE));
            if (navplace === -1) continue;
            const p3 = context.findIndex((c) => c.includes(P3));
            if (p3 === -1 || navplace > p3) wrong.push(file);
        }
        expect(wrong).toEqual([]);
    });

    test("every manifest that uses navPlace properties names the context", () => {
        const CONTEXT_URL = "https://cmahnke.github.io/StoryMapJS/navplace-properties.json";
        const missing: string[] = [];
        for (const file of shippedManifests()) {
            const raw = readFileSync(join(process.cwd(), "public/examples-iiif", file), "utf8");
            if (!raw.includes('"properties"')) continue;
            if (!raw.includes(CONTEXT_URL)) missing.push(file);
        }
        expect(missing).toEqual([]);
    });

    test("leaves no dropped term in any shipped manifest", () => {
        // A term replaced by a standard property in docs/plans/iiif-interop.md
        // §2 must be gone from the reader, the emitter, the context *and* every
        // manifest we ship. The fixture-drift test already pins the generated
        // ones to the converter; this is the independent check, and it also
        // covers the hand-authored georeferenced manifests.
        const DROPPED = [
            "storymap:mediaCaption",
            "storymap:mediaCredit",
            "storymap:mediaAlt",
            "storymap:date",
            "storymap:background",
            "storymap:iiifUrl",
            "storymap:imageRegion",
            "storymap:georeferencedLayers",
            "storymap:mapType",
        ];
        const offenders: string[] = [];
        for (const file of shippedManifests()) {
            const raw = readFileSync(join(process.cwd(), "public/examples-iiif", file), "utf8");
            for (const term of DROPPED) {
                if (raw.includes(`"${term}"`)) offenders.push(`${file} still carries ${term}`);
            }
        }
        expect(offenders).toEqual([]);
    });
});
