// Converts legacy StoryMap JSON fixtures (public/examples/*.json) into IIIF
// Presentation API 3.0 manifests (public/examples-iiif/<name>.json) following
// the mapping proposed in docs/storymap-as-iiif-manifest.md.
//
// Usage: node scripts/convert-to-iiif.mjs [files...]
// With no arguments, converts all public/examples/*.json fixtures.
//
// Every fixture in public/examples-iiif/ is generated here except
// georeferenced-layer.json and georeferenced-layer-unsupported.json, which
// are hand-authored: a georeferenced layer is a manifest-only feature
// (storymap JSON cannot express ground control points), so there is nothing
// to convert from.
//
// The mapping itself is exported as `storymapToManifest()` and is pure, so
// tests/iiif-roundtrip.test.ts can convert in-process: it asserts that
// regenerating a fixture is a no-op (so a hand edit to a generated file is
// caught) and that a manifest converts back to the storymap it came from. That
// is what makes each docs/plans/iiif-interop.md §2 term migration checkable
// as "unchanged in meaning" rather than by reading a fixture diff.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

// The original zoomify tile paths of the legacy fixtures are dead, so image-map
// storymaps are rewritten to the IIIF reference image used by the repo's IIIF
// fixtures. The original zoomify definition is preserved as a storymap: term.
const LAOCOON_ID =
    "https://iiif.io/api/image/3.0/example/reference/28473c77da3deebe4375c3a50572d9d3-laocoon";
const LAOCOON_INFO = `${LAOCOON_ID}/info.json`;
const LAOCOON_IMAGE = `${LAOCOON_ID}/full/max/0/default.jpg`;
const LAOCOON_WIDTH = 2315;
const LAOCOON_HEIGHT = 3000;

const STORYMAP_CONTEXT = "https://cmahnke.github.io/StoryMapJS/context.json";
const CONTEXTS = [
    "http://iiif.io/api/presentation/3/context.json",
    "http://iiif.io/api/extension/navplace/context.json",
    STORYMAP_CONTEXT,
];

const IMAGE_FORMATS = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    gif: "image/gif",
    webp: "image/webp",
    bmp: "image/bmp",
    avif: "image/avif",
};

const VIDEO_HOSTS = ["youtube.com", "youtu.be", "vimeo.com", "dailymotion.com", "vine.co"];
const SOUND_HOSTS = ["soundcloud.com"];

function isHttpUrl(value) {
    return typeof value === "string" && /^https?:\/\//i.test(value);
}

function classifyMediaUrl(url) {
    const ext = url.split(/[?#]/)[0].split(".").pop()?.toLowerCase();
    if (ext && IMAGE_FORMATS[ext]) {
        return { type: "Image", format: IMAGE_FORMATS[ext] };
    }
    let host;
    try {
        host = new URL(url).hostname.replace(/^www\./, "");
    } catch {
        return { type: "Text", format: "text/html" };
    }
    if (VIDEO_HOSTS.some((h) => host === h || host.endsWith(`.${h}`))) {
        return { type: "Video" };
    }
    if (SOUND_HOSTS.some((h) => host === h || host.endsWith(`.${h}`))) {
        return { type: "Sound" };
    }
    // Page-embedded media (tweets, Wikipedia, photo pages, ...) - the viewer
    // decides how to render these; the manifest carries a typed reference.
    return { type: "Text", format: "text/html" };
}

function languageMap(value) {
    return { none: [value] };
}

function present(value) {
    return value !== undefined && value !== null && value !== "";
}

export function storymapToManifest(name, legacy) {
    const storymap = legacy.storymap || {};
    const slides = storymap.slides || [];
    const isZoomify = storymap.map_type === "zoomify";
    const isImageMap = isZoomify || storymap.map_type === "iiif";
    const manifestId = `https://example.org/storymap/${name}`;
    const attribution = storymap.iiif?.attribution || storymap.zoomify?.attribution || "";

    const canvases = slides.map((slide, i) =>
        buildCanvas(manifestId, i, slide, isImageMap, i === 0 ? storymap.overlays : null),
    );

    const manifest = {
        "@context": CONTEXTS,
        id: manifestId,
        type: "Manifest",
        label: languageMap(name),
        behavior: ["paged"],
        // P3's `provider` is whoever *published* the content, and the
        // converter does not know that — it only knows what produced the
        // manifest, which is what `metadata` is for. Claiming to be the
        // provider would put "Provider: StoryMapJS" on the credit line of every
        // converted storymap (§3.2).
        metadata: [
            {
                label: languageMap("Generated by"),
                value: languageMap("StoryMapJS"),
            },
        ],
        items: canvases,
        // `structures` carries the groups (§3.5). A storymap states a slide's
        // group as a plain string; P3 states it as a Range over the canvases it
        // contains, and the reader turns that back into `slide.group`.
        ...buildStructures(manifestId, slides, canvases),
    };

    // A map bbox has no extension term: the interoperable spelling is a
    // navPlace Polygon, which the reader turns back into map_bbox
    // (readNavPlaceBbox). Without this the extent was silently lost on the
    // round trip.
    const bbox = storymap.map_bbox;
    if (isLonLatBox(bbox)) {
        const [west, south, east, north] = bbox;
        manifest.navPlace = {
            id: `${manifestId}/navplace`,
            type: "FeatureCollection",
            features: [
                {
                    id: `${manifestId}/navplace/feature/1`,
                    type: "Feature",
                    geometry: {
                        type: "Polygon",
                        coordinates: [
                            [
                                [west, south],
                                [east, south],
                                [east, north],
                                [west, north],
                                [west, south],
                            ],
                        ],
                    },
                    properties: {},
                },
            ],
        };
    }

    const config = buildMapConfig(storymap, legacy, isZoomify);
    if (Object.keys(config).length > 0) {
        // The Manifest object is closed for extension terms in the official
        // validator's JSON Schema (see docs "Validator interop"), so the
        // storymap map configuration travels on a dedicated service entry.
        manifest.service = [
            {
                id: `${manifestId}/map-config`,
                type: "Service",
                profile: `${STORYMAP_CONTEXT}/mapconfig`,
                ...config,
            },
        ];
    }
    if (present(attribution)) {
        manifest.requiredStatement = {
            label: languageMap("Attribution"),
            value: languageMap(attribution),
        };
    }
    return manifest;
}

function buildMapConfig(storymap, legacy, isZoomify) {
    const config = {};
    let mapType = storymap.map_type;
    if (isZoomify) {
        // zoomify support was replaced by the IIIF Image API; the legacy
        // pyramid definition is not carried (nothing reads it)
        mapType = "iiif";
        config["storymap:mapAsImage"] = true;
    }
    if (present(mapType)) {
        // A keyword basemap and a tile URL template are different kinds of
        // thing, and `mapType` used to be both. A keyword the viewer knows how
        // to configure is a `storymap:basemap`; anything with a {z} in it is
        // TileJSON's `tiles`, which is where a tile service belongs (§2.9).
        if (String(mapType).includes("{z}")) {
            config.tilejson = { tiles: mapType };
        } else {
            config["storymap:basemap"] = mapType;
        }
    }
    if (storymap.map_as_image !== undefined) {
        config["storymap:mapAsImage"] = storymap.map_as_image;
    }
    if (present(storymap.map_access_token)) {
        config["storymap:mapAccessToken"] = storymap.map_access_token;
    }
    if (present(storymap.map_background_color)) {
        config["storymap:mapBackgroundColor"] = storymap.map_background_color;
    }
    if (storymap.map_center_offset !== undefined) {
        config["storymap:mapCenterOffset"] = storymap.map_center_offset;
    }
    if (present(storymap.map_subdomains)) {
        config["storymap:mapSubdomains"] = storymap.map_subdomains;
    }
    const fontCss = legacy.font_css || storymap.font_css;
    if (present(fontCss)) {
        config["storymap:fontCss"] = fontCss;
    }
    if (storymap.call_to_action !== undefined) {
        config["storymap:callToAction"] = storymap.call_to_action;
    }
    if (present(storymap.call_to_action_text)) {
        config["storymap:callToActionText"] = storymap.call_to_action_text;
    }
    if (storymap.start_at_slide !== undefined) {
        config["storymap:startAtSlide"] = storymap.start_at_slide;
    }
    if (present(storymap.language)) {
        config["storymap:language"] = storymap.language;
    }
    if (storymap.calculate_zoom !== undefined) {
        config["storymap:calculateZoom"] = storymap.calculate_zoom;
    }
    if (storymap.less_bounce !== undefined) {
        config["storymap:lessBounce"] = storymap.less_bounce;
    }
    if (storymap.line_follows_path !== undefined) {
        config["storymap:lineFollowsPath"] = storymap.line_follows_path;
    }
    if (storymap.show_lines !== undefined) {
        config["storymap:showLines"] = storymap.show_lines;
    }
    if (storymap.show_history_line !== undefined) {
        config["storymap:showHistoryLine"] = storymap.show_history_line;
    }
    if (present(storymap.line_color)) {
        config["storymap:lineColor"] = storymap.line_color;
    }
    if (present(storymap.line_color_inactive)) {
        config["storymap:lineColorInactive"] = storymap.line_color_inactive;
    }
    if (storymap.line_weight !== undefined) {
        config["storymap:lineWeight"] = storymap.line_weight;
    }
    if (storymap.line_opacity !== undefined) {
        config["storymap:lineOpacity"] = storymap.line_opacity;
    }
    if (present(storymap.line_dash)) {
        config["storymap:lineDash"] = storymap.line_dash;
    }
    if (present(storymap.line_join)) {
        config["storymap:lineJoin"] = storymap.line_join;
    }
    if (storymap.use_custom_markers !== undefined) {
        config["storymap:useCustomMarkers"] = storymap.use_custom_markers;
    }
    if (storymap.map_area !== undefined) {
        config["storymap:mapArea"] = storymap.map_area;
    }
    if (isLonLatBox(storymap.overview_extent)) {
        config["storymap:overviewExtent"] = storymap.overview_extent;
    }
    if (storymap.keyboard !== undefined) {
        config["storymap:keyboard"] = storymap.keyboard;
    }
    if (Array.isArray(storymap.overlays) && storymap.overlays.length > 0) {
        // entries without a map_type are dropped on the way back in
        config["storymap:overlays"] = storymap.overlays.filter(
            (entry) => entry && present(entry.map_type),
        );
    }
    return config;
}

/** A `[west, south, east, north]` box of four finite numbers. */
function isLonLatBox(value) {
    return (
        Array.isArray(value) &&
        value.length === 4 &&
        value.every((n) => typeof n === "number" && Number.isFinite(n))
    );
}

function buildCanvas(manifestId, index, slide, isImageMap, georeferencedLayers) {
    const canvasId = `${manifestId}/canvas/${index + 1}`;
    const headline = slide.text?.headline || "";
    const bodyText = slide.text?.text || "";
    const width = isImageMap ? LAOCOON_WIDTH : 1080;
    const height = isImageMap ? LAOCOON_HEIGHT : 1080;

    const canvas = {
        id: canvasId,
        type: "Canvas",
        height,
        width,
        // P3 spells a slide's date `navDate`, and the official validator
        // constrains it to a plain string — a language map is rejected, and it
        // applies no format constraint at all, so the storymap value is
        // carried verbatim ("Aug 23" and "1790-2010" both pass) (§2.5)
        ...(typeof slide.date === "string" && slide.date !== "" ? { navDate: slide.date } : {}),
        // P3 paints a canvas background with an Annotation referenced from the
        // canvas `background` property (§2.6)
        ...buildBackground(canvasId, slide.background),
        // media.thumb is P3's `thumbnail`, a list of content resources (§3.1)
        ...buildThumbnail(slide),
        items: [
            {
                id: `${canvasId}/annotationpage/1`,
                type: "AnnotationPage",
                items: [
                    {
                        id: `${canvasId}/annotation/1`,
                        type: "Annotation",
                        motivation: "painting",
                        // P3 defines label / requiredStatement /
                        // accessibilitySummary on the Annotation, which is
                        // where a caption, a credit and alt text belong for
                        // the resource being painted (§2.7)
                        ...buildAnnotationPresentation(slide),
                        body: buildBody(slide, isImageMap),
                        target: buildRegionTarget(canvasId, slide.location?.region) ?? canvasId,
                    },
                    // Georeference Extension annotations for the placed rasters
                    // (§2.10). The layers are map-wide but an annotation is
                    // canvas-scoped, so they are written on the first canvas and
                    // the reader collects them from every canvas.
                    ...buildGeoreferencing(canvasId, georeferencedLayers),
                ],
            },
        ],
    };
    if (present(headline)) {
        canvas.label = languageMap(headline);
    }
    if (present(bodyText)) {
        canvas.summary = languageMap(bodyText);
    }

    const storymapTerms = buildCanvasTerms(slide);
    Object.assign(canvas, storymapTerms);

    const navPlace = buildNavPlace(canvasId, slide);
    if (navPlace) {
        canvas.navPlace = navPlace;
    }
    return canvas;
}

/**
 * A map's georeferenced rasters as Georeference Extension annotations
 * (§2.10).
 *
 * Per the extension, a layer that is not part of the canvas it ships in — which
 * is every placed raster — carries the image it places in `target` as an
 * embedded resource, and the ground control points in `body` as a
 * FeatureCollection whose features carry `resourceCoords`.
 *
 * The `opacity`, `visible`, `className` and `blendMode` the term could carry
 * have no IIIF vocabulary for a georeferencing annotation, so they are not
 * written; the attribution is, as a `requiredStatement`, which is where P3 puts
 * it.
 */
function buildGeoreferencing(canvasId, overlays) {
    const layers = (overlays || []).filter((entry) => entry && entry.georeference);
    return layers.map((entry) => {
        const georeference = entry.georeference;
        return {
            id: `${canvasId}/georeferencing/${layers.indexOf(entry) + 1}`,
            type: "Annotation",
            motivation: "georeferencing",
            target: {
                id: georeference.url,
                type: "Image",
                width: georeference.width,
                height: georeference.height,
                service: [{ id: georeference.url, type: "ImageService3", profile: "level2" }],
            },
            ...(present(entry.attribution)
                ? {
                      requiredStatement: {
                          label: languageMap("Attribution"),
                          value: languageMap(entry.attribution),
                      },
                  }
                : {}),
            body: georeference.body,
        };
    });
}

/**
 * A storymap's `slide.group` values as P3 `structures`: one Range per group,
 * over the canvases it contains (§3.5).
 *
 * Groups come out in first-appearance order, and the slides keep their order
 * within a group — which is what makes a grouped storymap's slide order the
 * concatenation of its groups, rather than the original interleaving. No group
 * anywhere means no `structures` at all.
 */
function buildStructures(manifestId, slides, canvases) {
    const groups = [];
    const byGroup = new Map();
    slides.forEach((slide, i) => {
        const group = slide.group;
        if (!present(group)) return;
        if (!byGroup.has(group)) {
            byGroup.set(group, []);
            groups.push(group);
        }
        byGroup.get(group).push(canvases[i].id);
    });
    if (groups.length === 0) return {};
    return {
        structures: groups.map((group, i) => ({
            id: `${manifestId}/range/${i + 1}`,
            type: "Range",
            label: languageMap(group),
            items: byGroup.get(group),
        })),
    };
}

/**
 * A slide's `media.thumb` as P3's canvas `thumbnail`, which is a list of
 * content resources (§3.1).
 */
function buildThumbnail(slide) {
    const url = slide.media?.thumb;
    if (!present(url)) return {};
    const { type, format } = classifyMediaUrl(url);
    return { thumbnail: [{ id: url, type, ...(format ? { format } : {}) }] };
}

/**
 * A slide background as P3's canvas `background`: a painting Annotation whose
 * body is the image and/or the colour to paint behind the slide (§2.6). A
 * bare-string background is a colour, as it has always been in storymap-JSON.
 *
 * `background.opacity` is deliberately not carried across. IIIF has no
 * vocabulary for it — Presentation 3 has a `Color` body but nothing to fade a
 * background with, and 4.0's `backgroundColor` is a plain hex value — and the
 * viewer never rendered it, so a term for it would be dead vocabulary.
 */
function buildBackground(canvasId, background) {
    if (!background) return {};
    const object = typeof background === "object" ? background : {};
    const url = typeof background === "string" ? null : object.url;
    const color = typeof background === "string" ? background : object.color;
    const bodies = [];
    if (present(url)) {
        const { type, format } = classifyMediaUrl(url);
        bodies.push({ id: url, type, ...(format ? { format } : {}) });
    }
    if (present(color)) {
        bodies.push({ type: "Color", value: color });
    }
    if (bodies.length === 0) return {};
    return {
        background: {
            id: `${canvasId}/background`,
            type: "Annotation",
            motivation: "painting",
            body: bodies.length === 1 ? bodies[0] : bodies,
            target: canvasId,
        },
    };
}

/**
 * A slide's media caption, credit and alt text as the painting annotation's
 * own P3 properties, replacing the `storymap:mediaCaption` /
 * `mediaCredit` / `mediaAlt` canvas terms (§2.7).
 *
 * `requiredStatement` is a single `{label, value}` object in P3 — the official
 * validator rejects the array form — so the credit becomes a labelled
 * statement, and §2.1's reader turns it back into "Credit: …".
 */
function buildAnnotationPresentation(slide) {
    const out = {};
    if (present(slide.media?.caption)) {
        out.label = languageMap(slide.media.caption);
    }
    if (present(slide.media?.credit)) {
        out.requiredStatement = {
            label: languageMap("Credit"),
            value: languageMap(slide.media.credit),
        };
    }
    if (present(slide.media?.alt)) {
        out.accessibilitySummary = languageMap(slide.media.alt);
    }
    return out;
}

function buildBody(slide, isImageMap) {
    if (isImageMap) {
        // Image-map canvas: paint the IIIF Image API resource. The service
        // reference lets IIIF-aware viewers request arbitrary resolutions.
        return {
            id: LAOCOON_IMAGE,
            type: "Image",
            format: "image/jpeg",
            width: LAOCOON_WIDTH,
            height: LAOCOON_HEIGHT,
            service: [{ id: LAOCOON_INFO, type: "ImageService3", profile: "level2" }],
        };
    }
    const url = slide.media?.url;
    if (isHttpUrl(url)) {
        const { type, format } = classifyMediaUrl(url);
        const body = { id: url, type };
        if (format) {
            body.format = format;
        }
        return body;
    }
    // Text-only slide (or a media value that is not a URL): paint the HTML.
    const html = typeof url === "string" && url !== "" ? url : slide.text?.text || "";
    return {
        type: "TextualBody",
        format: "text/html",
        value: html,
    };
}

function buildCanvasTerms(slide) {
    const terms = {};
    if (slide.type === "overview") {
        terms["storymap:type"] = "overview";
    }
    if (present(slide.media?.srcset)) {
        terms["storymap:mediaSrcset"] = slide.media.srcset;
    }
    if (present(slide.media?.sizes)) {
        terms["storymap:mediaSizes"] = slide.media.sizes;
    }
    return terms;
}

/**
 * A slide's `location.region` as the painting annotation's target, so the
 * region is an Image API selector rather than a term (§2.8).
 *
 * `xywh=pixel:` rather than a bare `xywh=` because the field is documented in
 * image pixels, and the prefix then says so itself instead of implying the
 * canvas size — which matters for a non-image map, where the canvas is a
 * nominal 1080×1080 and the region's image is something else entirely. It is
 * the prefix Media Fragments 1.0 defines for source-image pixels; `image:` is
 * not one of the three it defines.
 */
function buildRegionTarget(canvasId, region) {
    if (!Array.isArray(region) || region.length !== 4) return null;
    if (!region.every((n) => typeof n === "number" && Number.isFinite(n))) return null;
    return {
        type: "SpecificResource",
        source: canvasId,
        selector: { type: "ImageApiSelector", value: `xywh=pixel:${region.join(",")}` },
    };
}

function buildNavPlace(canvasId, slide) {
    const location = slide.location || {};
    if (typeof location.lat !== "number" || typeof location.lon !== "number") {
        return null;
    }
    const properties = {};
    for (const key of ["name", "zoom", "line", "icon", "iconSize", "image", "use_custom_marker"]) {
        if (location[key] !== undefined && location[key] !== null && location[key] !== "") {
            properties[key] = location[key];
        }
    }
    return {
        id: `${canvasId}/navplace`,
        type: "FeatureCollection",
        features: [
            {
                id: `${canvasId}/navplace/feature/1`,
                type: "Feature",
                geometry: { type: "Point", coordinates: [location.lon, location.lat] },
                properties,
            },
        ],
    };
}

/** True when this file is the process entry point, not an import. */
const invokedDirectly =
    process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

function main() {
    const args = process.argv.slice(2);
    let files;
    if (args.length > 0) {
        files = args;
    } else {
        const examplesDir = join(process.cwd(), "public/examples");
        files = readdirSync(examplesDir)
            .filter((f) => f.endsWith(".json"))
            .map((f) => join(examplesDir, f));
    }

    const outDir = join(process.cwd(), "public/examples-iiif");
    mkdirSync(outDir, { recursive: true });

    let converted = 0;
    for (const file of files) {
        const name = file
            .split("/")
            .pop()
            .replace(/\.json$/, "");
        const legacy = JSON.parse(readFileSync(file, "utf8"));
        const manifest = storymapToManifest(name, legacy);
        const outPath = join(outDir, `${name}.json`);
        writeFileSync(outPath, `${JSON.stringify(manifest, null, 4)}\n`);
        converted++;
        console.log(`✓ ${outPath} (${manifest.items.length} canvas(es))`);
    }
    console.log(`Converted ${converted} storymap(s) to ${outDir}/`);
}

if (invokedDirectly) {
    main();
}
